license="MIT"
modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/DynamicTreesTeam/DynamicTrees/issues"

[[mods]]
modId="dt_inventorypets"
version="${file.jarVersion}"
displayName="Dynamic Trees for Inventory Pets"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamictrees"
logoFile="logo.png"
credits=""
authors="WenXin2"
description='''
Adds Dynamic Trees compatibility for Inventory Pets.
'''

[[dependencies.dt_inventorypets]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dt_inventorypets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dt_inventorypets]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.3.6,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dt_inventorypets]]
    modId="inventorypets"
    mandatory=true
    versionRange="[2.1.3,)"
    ordering="AFTER"
    side="BOTH"